import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EmailProvider } from "@/component/EmailState";
import AuthGuard from "@/component/AuthGuard";
import { Analytics } from '@vercel/analytics/next';
import { dark } from '@clerk/themes'
import {
  ClerkProvider

} from '@clerk/nextjs'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ketflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
    }}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthGuard />
          <EmailProvider>
            {children}
            <Analytics />
          </EmailProvider>

        </body>
      </html>
    </ClerkProvider>

  );
}
